CREATE TABLE [dbo].[Contact]
(
	[Id] INT NOT NULL IDENTITY,
	[LastName] NVARCHAR(50) NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(320) NOT NULL,
	[Phone] NVARCHAR(30) NOT NULL,
    CONSTRAINT [PK_Contact] PRIMARY KEY ([Id])
)
